[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  # Limit included files to reduce function size
  included_files = [
    "src/app/api/search/**",
    ".env*"
  ]
  external_node_modules = ["next"]

# Function-specific configuration
[functions."api/search"]
  # Only include necessary files
  included_files = [
    "src/app/api/search/**",
    ".env*"
  ]
  external_node_modules = ["next"]

[[headers]]
  for = "/api/search"
  [headers.values]
    "Access-Control-Allow-Origin" = "*"
    "Access-Control-Allow-Methods" = "GET, POST, OPTIONS"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"