[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["**"]
  external_node_modules = ["next"]

# This is the correct way to set function timeout in Netlify
[functions."api/search"]
  included_files = ["**"]
  node_bundler = "esbuild"
  external_node_modules = ["next"]

# Add this section to properly set the timeout
[[headers]]
  for = "/api/search"
  [headers.values]
    "Access-Control-Allow-Origin" = "*"
    "Access-Control-Allow-Methods" = "GET, POST, OPTIONS"
